services:
  #  stats-server:
  #    build: ./stats/stats-server
  #    container_name: stats-server
  #    ports:
  #      - "9090:9090"
  #    depends_on:
  #      - stats-db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
  #      - SPRING_DATASOURCE_USERNAME=stats
  #      - SPRING_DATASOURCE_PASSWORD=stats
  #
  #  ewm-service:
  #    build: ./main-service
  #    container_name: ewm-service
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - ewm-db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
  #      - SPRING_DATASOURCE_USERNAME=ewm
  #      - SPRING_DATASOURCE_PASSWORD=ewm

  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats_server
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:17.5
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://postgres:12345@postgres:5432 -v ON_ERROR_STOP=1 <<-EOSQL
        create database core_event_service;
        create database core_user_service;
        create database core_request_service;
        EOSQL