kafka:
  bootstrap-servers: localhost:9092
  action-topic: stats.user-actions.v1
  similarity-topic: stats.events-similarity.v1
  auto-commit: false
  group-id: action-group

user-action:
  view: 0.4
  register: 0.8
  like: 1.0
